apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: db-ns
  labels:
    app: lunch-app
    tier: database
spec:
  clusterIP: None
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: lunch-app
    tier: database
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  namespace: db-ns
  labels:
    app: lunch-app
    tier: database
spec:
  serviceName: "mongo"
  replicas: 1
  selector:
    matchLabels:
      app: lunch-app
      tier: database
  template:
    metadata:
      labels:
        app: lunch-app
        tier: database
    spec:
      imagePullSecrets:
        - name: private-reg-secret
      containers:
        - name: mongo
          image: 192.168.0.220/lunchapp/mongo:7.0   # Harbor 경로 유지
          ports:
            - containerPort: 27017
          command: ["mongod", "--bind_ip_all"]
          env:
            - name: MONGO_INITDB_DATABASE
              value: "app"
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: lunch-app-secrets
                  key: MONGO_ROOT_USER
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: lunch-app-secrets
                  key: MONGO_ROOT_PASS
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
      volumes:
        - name: mongo-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-db-service
  namespace: db-ns
  labels:
    app: lunch-app
    tier: database
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
  selector:
    app: lunch-app
    tier: database

