apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: db-allow-from-back
  namespace: db-ns
spec:
  # ✅ 실제 mongo-0 Pod 라벨과 맞춤
  podSelector:
    matchLabels:
      app: lunch-app
      tier: database
  policyTypes:
  - Ingress
  ingress:
  - from:
    # 1) 같은 db-ns 안의 Pod 들 허용 (필요에 따라 옵션)
    - podSelector: {}

    # 2) back-ns 의 백엔드 Pod 허용 (백엔드만 DB 접근 가능)
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: back-ns
      podSelector:
        matchLabels:
          app: lunch-app-back
          tier: backend
    ports:
    - protocol: TCP
      port: 27017
