apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: db-allow-from-back
  namespace: db-ns
spec:
  podSelector:
    matchLabels:
      app: lunch-app        # 실제 mongo-0 라벨
      tier: database
  policyTypes:
  - Ingress
  ingress:
  - from:
    # 같은 db-ns 안 Pod 허용 (필요 없으면 지워도 됨)
    - podSelector: {}

    # back-ns 의 백엔드 Pod 허용
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: back-ns
      podSelector:
        matchLabels:
          app: lunch-app-back
          tier: backend
    ports:
    - protocol: TCP
      port: 27017

